openapi: 3.0.3
info:
  contact:
    email: hi@ory.sh
  description: |
    Documentation for all of Ory Keto's REST APIs. gRPC is documented separately.
  license:
    name: Apache 2.0
  title: Ory Keto API
servers:
- url: /
paths:
  /admin/relation-tuples:
    delete:
      description: Use this endpoint to delete relation tuples
      operationId: deleteRelationTuples
      parameters:
      - description: Namespace of the Relation Tuple
        explode: true
        in: query
        name: namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Relation Tuple
        explode: true
        in: query
        name: object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Relation Tuple
        explode: true
        in: query
        name: relation
        required: false
        schema:
          type: string
        style: form
      - description: SubjectID of the Relation Tuple
        explode: true
        in: query
        name: subject_id
        required: false
        schema:
          type: string
        style: form
      - description: Namespace of the Subject Set
        explode: true
        in: query
        name: subject_set.namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Subject Set
        explode: true
        in: query
        name: subject_set.object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Subject Set
        explode: true
        in: query
        name: subject_set.relation
        required: false
        schema:
          type: string
        style: form
      responses:
        "204":
          description: Empty responses are sent when, for example, resources are deleted.
            The HTTP status code for empty responses is typically 201.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Delete Relation Tuples
      tags:
      - write
    patch:
      description: Use this endpoint to patch one or more relation tuples.
      operationId: patchRelationTuples
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/PatchDelta'
              type: array
        x-originalParamName: Payload
      responses:
        "204":
          description: Empty responses are sent when, for example, resources are deleted.
            The HTTP status code for empty responses is typically 201.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Patch Multiple Relation Tuples
      tags:
      - write
    put:
      description: Use this endpoint to create a relation tuple.
      operationId: createRelationTuple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationQuery'
        x-originalParamName: Payload
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelationQuery'
          description: RelationQuery
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Create a Relation Tuple
      tags:
      - write
  /health/alive:
    get:
      description: |-
        This endpoint returns a HTTP 200 status code when Ory Keto is accepting incoming
        HTTP requests. This status does currently not include checks whether the database connection is working.

        If the service supports TLS Edge Termination, this endpoint does not require the
        `X-Forwarded-Proto` header to be set.

        Be aware that if you are running multiple nodes of this service, the health status will never
        refer to the cluster state, only to a single instance.
      operationId: isAlive
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Ory Keto is ready to accept connections.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Check HTTP Server Status
      tags:
      - metadata
  /health/ready:
    get:
      description: |-
        This endpoint returns a HTTP 200 status code when Ory Keto is up running and the environment dependencies (e.g.
        the database) are responsive as well.

        If the service supports TLS Edge Termination, this endpoint does not require the
        `X-Forwarded-Proto` header to be set.

        Be aware that if you are running multiple nodes of Ory Keto, the health status will never
        refer to the cluster state, only to a single instance.
      operationId: isReady
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Ory Keto is ready to accept requests.
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_503'
          description: Ory Kratos is not yet ready to accept requests.
      summary: Check HTTP Server and Database Status
      tags:
      - metadata
  /relation-tuples:
    get:
      description: Get all relation tuples that match the query. Only the namespace
        field is required.
      operationId: getRelationTuples
      parameters:
      - explode: true
        in: query
        name: page_token
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: page_size
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - description: Namespace of the Relation Tuple
        explode: true
        in: query
        name: namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Relation Tuple
        explode: true
        in: query
        name: object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Relation Tuple
        explode: true
        in: query
        name: relation
        required: false
        schema:
          type: string
        style: form
      - description: SubjectID of the Relation Tuple
        explode: true
        in: query
        name: subject_id
        required: false
        schema:
          type: string
        style: form
      - description: Namespace of the Subject Set
        explode: true
        in: query
        name: subject_set.namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Subject Set
        explode: true
        in: query
        name: subject_set.object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Subject Set
        explode: true
        in: query
        name: subject_set.relation
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getRelationTuplesResponse'
          description: getRelationTuplesResponse
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Query relation tuples
      tags:
      - read
  /relation-tuples/check:
    get:
      description: To learn how relation tuples and the check works, head over to
        [the documentation](../concepts/relation-tuples.mdx).
      operationId: getCheck
      parameters:
      - description: Namespace of the Relation Tuple
        explode: true
        in: query
        name: namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Relation Tuple
        explode: true
        in: query
        name: object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Relation Tuple
        explode: true
        in: query
        name: relation
        required: false
        schema:
          type: string
        style: form
      - description: SubjectID of the Relation Tuple
        explode: true
        in: query
        name: subject_id
        required: false
        schema:
          type: string
        style: form
      - description: Namespace of the Subject Set
        explode: true
        in: query
        name: subject_set.namespace
        required: false
        schema:
          type: string
        style: form
      - description: Object of the Subject Set
        explode: true
        in: query
        name: subject_set.object
        required: false
        schema:
          type: string
        style: form
      - description: Relation of the Subject Set
        explode: true
        in: query
        name: subject_set.relation
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: max-depth
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCheckResponse'
          description: getCheckResponse
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCheckResponse'
          description: getCheckResponse
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Check a relation tuple
      tags:
      - read
    post:
      description: To learn how relation tuples and the check works, head over to
        [the documentation](../concepts/relation-tuples.mdx).
      operationId: postCheck
      parameters:
      - explode: true
        in: query
        name: max-depth
        required: false
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationQuery'
        x-originalParamName: Payload
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCheckResponse'
          description: getCheckResponse
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCheckResponse'
          description: getCheckResponse
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Check a relation tuple
      tags:
      - read
  /relation-tuples/expand:
    get:
      description: Use this endpoint to expand a relation tuple.
      operationId: getExpand
      parameters:
      - description: Namespace of the Subject Set
        explode: true
        in: query
        name: namespace
        required: true
        schema:
          type: string
        style: form
      - description: Object of the Subject Set
        explode: true
        in: query
        name: object
        required: true
        schema:
          type: string
        style: form
      - description: Relation of the Subject Set
        explode: true
        in: query
        name: relation
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: max-depth
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/expandTree'
          description: expandTree
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Expand a Relation Tuple
      tags:
      - read
  /version:
    get:
      description: |-
        This endpoint returns the version of Ory Keto.

        If the service supports TLS Edge Termination, this endpoint does not require the
        `X-Forwarded-Proto` header to be set.

        Be aware that if you are running multiple nodes of this service, the version will never
        refer to the cluster state, only to a single instance.
      operationId: getVersion
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Returns the Ory Keto version.
      summary: Return Running Software Version.
      tags:
      - metadata
components:
  responses:
    emptyResponse:
      description: Empty responses are sent when, for example, resources are deleted.
        The HTTP status code for empty responses is typically 201.
  schemas:
    InternalRelationTuple:
      example:
        subject_id: subject_id
        namespace: namespace
        object: object
        relation: relation
        subject_set:
          namespace: namespace
          object: object
          relation: relation
      properties:
        namespace:
          description: Namespace of the Relation Tuple
          type: string
        object:
          description: Object of the Relation Tuple
          type: string
        relation:
          description: Relation of the Relation Tuple
          type: string
        subject_id:
          description: |-
            SubjectID of the Relation Tuple

            Either SubjectSet or SubjectID are required.
          type: string
        subject_set:
          $ref: '#/components/schemas/SubjectSet'
      required:
      - namespace
      - object
      - relation
      type: object
    PatchDelta:
      example:
        relation_tuple:
          subject_id: subject_id
          namespace: namespace
          object: object
          relation: relation
          subject_set:
            namespace: namespace
            object: object
            relation: relation
        action: insert
      properties:
        action:
          enum:
          - insert
          - delete
          type: string
        relation_tuple:
          $ref: '#/components/schemas/InternalRelationTuple'
      type: object
    RelationQuery:
      example:
        subject_id: subject_id
        namespace: namespace
        object: object
        relation: relation
        subject_set:
          namespace: namespace
          object: object
          relation: relation
      properties:
        namespace:
          description: Namespace of the Relation Tuple
          type: string
        object:
          description: Object of the Relation Tuple
          type: string
        relation:
          description: Relation of the Relation Tuple
          type: string
        subject_id:
          description: |-
            SubjectID of the Relation Tuple

            Either SubjectSet or SubjectID can be provided.
          type: string
        subject_set:
          $ref: '#/components/schemas/SubjectSet'
      type: object
    SubjectSet:
      example:
        namespace: namespace
        object: object
        relation: relation
      properties:
        namespace:
          description: Namespace of the Subject Set
          type: string
        object:
          description: Object of the Subject Set
          type: string
        relation:
          description: Relation of the Subject Set
          type: string
      required:
      - namespace
      - object
      - relation
      type: object
    UUID:
      format: uuid4
      type: string
    expandTree:
      example:
        subject_id: subject_id
        children:
        - null
        - null
        type: union
        subject_set:
          namespace: namespace
          object: object
          relation: relation
      properties:
        children:
          items:
            $ref: '#/components/schemas/expandTree'
          type: array
        subject_id:
          type: string
        subject_set:
          $ref: '#/components/schemas/SubjectSet'
        type:
          enum:
          - union
          - exclusion
          - intersection
          - leaf
          type: string
      required:
      - type
      type: object
    genericError:
      description: The standard error format
      properties:
        code:
          format: int64
          type: integer
        details:
          items:
            additionalProperties: true
            type: object
          type: array
        message:
          type: string
        reason:
          type: string
        request:
          type: string
        status:
          type: string
      type: object
    getCheckResponse:
      description: The content of the allowed field is mirrored in the HTTP status
        code.
      example:
        allowed: true
      properties:
        allowed:
          description: whether the relation tuple is allowed
          type: boolean
      required:
      - allowed
      title: RESTResponse is the response for a check request.
      type: object
    getRelationTuplesResponse:
      example:
        next_page_token: next_page_token
        relation_tuples:
        - subject_id: subject_id
          namespace: namespace
          object: object
          relation: relation
          subject_set:
            namespace: namespace
            object: object
            relation: relation
        - subject_id: subject_id
          namespace: namespace
          object: object
          relation: relation
          subject_set:
            namespace: namespace
            object: object
            relation: relation
      properties:
        next_page_token:
          description: |-
            The opaque token to provide in a subsequent request
            to get the next page. It is the empty string iff this is
            the last page.
          type: string
        relation_tuples:
          items:
            $ref: '#/components/schemas/InternalRelationTuple'
          type: array
      type: object
    healthNotReadyStatus:
      properties:
        errors:
          additionalProperties:
            type: string
          description: Errors contains a list of errors that caused the not ready
            status.
          type: object
      type: object
    healthStatus:
      properties:
        status:
          description: Status always contains "ok".
          type: string
      type: object
    subject:
      type: object
    version:
      properties:
        version:
          description: Version is the service's version.
          type: string
      type: object
    inline_response_200:
      example:
        status: status
      properties:
        status:
          description: Always "ok".
          type: string
      required:
      - status
      type: object
    inline_response_503:
      properties:
        errors:
          additionalProperties:
            type: string
          description: Errors contains a list of errors that caused the not ready
            status.
          type: object
      required:
      - errors
      type: object
    inline_response_200_1:
      example:
        version: version
      properties:
        version:
          description: The version of Ory Keto.
          type: string
      required:
      - version
      type: object
